
scr_debug_scripts_update()

scr_debug_show_var("right_free", right_free)
scr_debug_show_var("left_free", left_free)
scr_debug_show_var("down_free", down_free)
scr_debug_show_var("up_free", up_free)
scr_debug_show_var("hsp", hsp)
scr_debug_show_var("vsp", vsp)
scr_debug_show_var("collider_hsp", collider_hsp)
scr_debug_show_var("collider_vsp", collider_vsp)
scr_debug_show_var("state", state)
scr_debug_show_var("y", y)
scr_debug_show_var("dirsign", dirsign)
scr_debug_show_var("dir", dir)
//scr_debug_show_var("last_platform_left", last_platform_left)
//scr_debug_show_var("last_platform_right", last_platform_right)
//scr_debug_show_var("moving_collider", moving_collider)
//scr_debug_show_var("moving_collision", moving_collision)
//scr_debug_show_var("on_platform", on_platform)
scr_debug_show_var("is_colliding", is_colliding)
