
scr_debug_show_var("input dir", input_dir)
scr_debug_show_var("move_v", move_v)
scr_debug_show_var("move_h", move_h)
scr_debug_show_var("hsp_to", hsp_to)
scr_debug_show_var("vsp_to", vsp_to)
scr_debug_show_var("shoot_h", shoot_h)
scr_debug_show_var("shoot_v", shoot_v)
scr_debug_show_var("planet", current_planet)
scr_debug_show_var("gravx", gravx)
scr_debug_show_var("gravy", gravy)
scr_debug_show_var("resources", string(resources))
scr_debug_show_var("damage", string(dmg))
