
scr_debug_show_var("hp", string(hp))
scr_debug_show_var("damage", string(weapon.dmg))
scr_debug_show_var("speed", string(sp.normal))
scr_debug_show_var("cruise speed", string(sp.cruise))
scr_debug_show_var("", "")
scr_debug_show_var("cargo", string(cargo_load) + "/" + string(cargo))
scr_debug_show_var("fuel", string(tank_load) + "/" + string(tank))
scr_debug_show_var("", "")
//scr_debug_show_var("ore", string(resources[$ "ore"]))
//scr_debug_show_var("organic", string(resources[$ "organic"]))
//scr_debug_show_var("metal", string(resources[$ "metall"]))
//scr_debug_show_var("parts", string(resources[$ "part"]))
//scr_debug_show_var("junk", string(resources[$ "junk"]))
var names = variable_struct_get_names(resources)
for (var i = 0; i < array_length(names); ++i) {
    var nm = names[i]
	scr_debug_show_var(nm, string(resources[$ nm]))
}
scr_debug_show_var("", "")
//scr_debug_show_var("weapon", use_weapon_arr[use_weapon_index])
//draw_text(100, 30, string(resources))
//scr_debug_show_var("x", x)
//scr_debug_show_var("y", y)
//scr_debug_show_var("in_cruise_mode", string(in_cruise_mode))
//scr_debug_show_var("cruise_dir_to", string(cruise_dir_to))
//scr_debug_show_var("cruise_sp", string(cruise_sp))


//scr_debug_show_var("input dir", input_dir)
//scr_debug_show_var("move_v", move_v)
//scr_debug_show_var("move_h", move_h)
//scr_debug_show_var("hsp_to", hsp_to)
//scr_debug_show_var("vsp_to", vsp_to)
//scr_debug_show_var("shoot_h", shoot_h)
//scr_debug_show_var("shoot_v", shoot_v)
//scr_debug_show_var("planet", current_planet)
//scr_debug_show_var("gravx", gravx)
//scr_debug_show_var("gravy", gravy)
//scr_debug_show_var("resources", string(resources))
//scr_debug_show_var("damage", string(dmg))
